# Generated by Django 3.1.1 on 2020-10-31 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asisten',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_asisten', models.CharField(max_length=100, null=True)),
                ('nim', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dosen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_dosen', models.CharField(max_length=100)),
                ('id_dosen', models.CharField(blank=True, max_length=100, null=True)),
                ('no_hp', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_group', models.CharField(max_length=100, null=True)),
                ('semester', models.CharField(blank=True, max_length=50, null=True)),
                ('size', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mata_kuliah',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_matkul', models.CharField(max_length=100, null=True)),
                ('semester', models.CharField(blank=True, max_length=50)),
                ('islab', models.CharField(default='0', max_length=2)),
                ('code', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ruangan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_ruangan', models.CharField(max_length=100, null=True)),
                ('kapasitas', models.CharField(blank=True, max_length=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Waktu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mulai', models.CharField(max_length=100, null=True)),
                ('berakhir', models.CharField(max_length=50, null=True)),
                ('hari', models.CharField(max_length=50, null=True)),
                ('islab', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='GroupByMatkul',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='penjadwalan.group')),
                ('id_matkul', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='penjadwalan.mata_kuliah')),
            ],
            options={
                'verbose_name': 'GroupByMatkul',
                'verbose_name_plural': 'GroupByMatkul',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DosenByMatkul',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_dosen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='penjadwalan.dosen')),
                ('id_matkul', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='penjadwalan.mata_kuliah')),
            ],
        ),
        migrations.CreateModel(
            name='AsistenByMatkul',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_asisten', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='penjadwalan.asisten')),
                ('id_matkul', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='penjadwalan.mata_kuliah')),
            ],
        ),
    ]
